### ISSUE TITLE
Grafana not opening port 3000

### ISSUE THREAD

**Issue by nzjc** [ksator/junos_monitoring_with_a_TIG_stack#5]
Have followed the instructions in the wiki, except I am using Ubuntu 18.. All containers start up fine following `make up`, but netstat (and external machines) can't see port 3000 open for Grafana.

```
me$ sudo netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      7554/systemd-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      8459/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      8459/sshd
tcp6       0      0 :::9081                 :::*                    LISTEN      26450/docker-proxy
```

Truncated logs from the grafana container:

```
t=2019-12-23T21:16:13+0000 lvl=info msg="Initializing Stream Manager"
t=2019-12-23T21:16:13+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
```

telnet on 3000 from outside just fails, nmap shows the port is not open.

Docker ps shows:

```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                          NAMES
6e114db8395f        grafana/grafana:5.4.2           "/run.sh"                4 hours ago         Up 54 minutes       0.0.0.0:9081->3000/tcp         grafana
```

Is this due to not running docker as root? 

Thanks

**Comment by ksator** [comment]
hello @nzjc the [docker-compose file](https://github.com/ksator/junos_monitoring_with_a_TIG_stack/blob/master/docker-compose.yml) in this repo is using the external port 9081 for grafana.

**Comment by nzjc** [comment]
Sorry it took me so long to respond. That's good to know, but your instructions on the wiki say:

`You can now use the Grafana GUI http://host_ip_address:3000.` 

I think this should be `You can now use the Grafana GUI http://host_ip_address:9081.`
